import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import { Waypoint } from 'react-waypoint';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { MinimalPosts } from '../components/minimal-posts';
import { PersonalHeader } from '../components/personal-theme-header';
import {
	FaGithub, 
	FaLinkedin, 
	FaInstagram, 
	FaRss,
	FaGlobe,
} from 'react-icons/fa';
import { 
	SiHashnode,
	SiX,
} from 'react-icons/si';
import {
	MorePostsByPublicationDocument,
	MorePostsByPublicationQuery,
	MorePostsByPublicationQueryVariables,
	PageInfoFragment,
	PostFragment,
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
	PublicationFragment,
} from '../generated/graphql';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;

type Props = {
	publication: PublicationFragment;
	initialPosts: PostFragment[];
	initialPageInfo: PageInfoFragment;
};

export default function Index({ publication, initialPosts, initialPageInfo }: Props) {
	const [posts, setPosts] = useState<PostFragment[]>(initialPosts);
	const [pageInfo, setPageInfo] = useState<Props['initialPageInfo']>(initialPageInfo);
	const [loadedMore, setLoadedMore] = useState(false);

	const loadMore = async () => {
		const data = await request<MorePostsByPublicationQuery, MorePostsByPublicationQueryVariables>(
			GQL_ENDPOINT,
			MorePostsByPublicationDocument,
			{
				first: 20,
				host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
				after: pageInfo.endCursor,
			},
		);
		if (!data.publication) {
			return;
		}
		const newPosts = data.publication.posts.edges.map((edge) => edge.node);
		setPosts([...posts, ...newPosts]);
		setPageInfo(data.publication.posts.pageInfo);
		setLoadedMore(true);
	};
	return (
		<AppProvider publication={publication}>
			<Layout>
				<Head>
					<title>{publication.title}</title>
					<meta
						name="description"
						content={
							publication.descriptionSEO || publication.title || `${publication.author.name}'s Blog`
						}
					/>
					<meta property="twitter:card" content="summary_large_image"/>
					<meta property="twitter:title" content={publication.displayTitle || publication.title || 'Hashnode Blog Starter Kit'} />
					<meta property="twitter:description" content={publication.descriptionSEO || publication.title || `${publication.author.name}'s Blog`} />
					<meta
						property="og:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<meta
						property="twitter:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{
							__html: JSON.stringify(addPublicationJsonLd(publication)),
						}}
					/>
				</Head>
				<Container className="mx-auto flex max-w-3xl flex-col items-stretch gap-6 sm:gap-8 md:gap-10 py-6 sm:py-8 md:py-10 min-h-full">
					<PersonalHeader />
					
					{/* About this publication */}
					<div className="space-y-6 sm:space-y-8 rounded-2xl border border-white/40 dark:border-slate-700/40 bg-white/40 dark:bg-slate-900/40 backdrop-blur-2xl p-4 sm:p-6 shadow-glass-light dark:shadow-glass-dark">
						{/* Author Info */}
						{publication.author && (
							<div className="space-y-3 sm:space-y-4">
								<div className="flex items-center gap-3 sm:gap-4">
									{publication.author.profilePicture && (
										<Image
											src={publication.author.profilePicture}
											alt={publication.author.name}
											className="h-12 w-12 sm:h-16 sm:w-16 rounded-full shrink-0"
											width={64}
											height={64}
										/>
									)}
									<div className="min-w-0 flex-1">
										<p className="font-medium text-sm sm:text-base text-slate-900 dark:text-white">
											{publication.author.name}
										</p>
										{publication.author.tagline && (
											<p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 mt-1">
												{publication.author.tagline}
											</p>
										)}
									</div>
								</div>
								{publication.author.bio?.html && (
									<div 
										className="prose prose-xs sm:prose-sm prose-slate dark:prose-invert max-w-none"
										dangerouslySetInnerHTML={{ __html: publication.author.bio.html }}
									/>
								)}
							</div>
						)}

						{/* About Publication */}
						<div className="space-y-3 sm:space-y-4 border-t border-white/30 dark:border-slate-700/30 pt-4 sm:pt-6 backdrop-blur-sm">
							<h2 className="text-lg sm:text-xl font-bold text-slate-900 dark:text-white">
								About this publication
							</h2>
							{publication.about?.html ? (
								<div 
									className="prose prose-sm sm:prose-base prose-slate dark:prose-invert max-w-none"
									dangerouslySetInnerHTML={{ __html: publication.about.html }}
								/>
							) : (
								<p className="text-sm sm:text-base text-slate-500 dark:text-slate-400">
									{publication.descriptionSEO || `Welcome to ${publication.title}'s blog.`}
								</p>
							)}
						</div>

						{/* Debug output */}
						<div className="hidden">
							{JSON.stringify({ publication, authorSocialLinks: publication.author?.socialMediaLinks }, null, 2)}
						</div>
						
						{/* Social Links */}
						{publication.links && (
							<div className="border-t border-white/30 dark:border-slate-700/30 pt-4 sm:pt-6 backdrop-blur-sm">
								<div className="flex flex-wrap items-center gap-2 sm:gap-3">
									{/* RSS Link */}
									<a
										href="/rss.xml"
										target="_blank"
										rel="noopener noreferrer"
										className="group flex items-center justify-center w-8 h-8 rounded-lg bg-white/40 dark:bg-slate-800/40 backdrop-blur-sm border border-white/30 dark:border-slate-700/30 text-slate-600 hover:text-orange-500 dark:text-slate-400 dark:hover:text-orange-400 hover:bg-white/60 dark:hover:bg-slate-800/60 hover:border-orange-300/50 dark:hover:border-orange-500/50 transition-all duration-200 shadow-sm hover:shadow-md"
										title="RSS Feed"
										aria-label="RSS Feed"
									>
										<FaRss className="w-4 h-4" />
									</a>
									{/* Twitter/X Link */}
									{publication.links.twitter && (
										<a
											href={publication.links.twitter}
											target="_blank"
											rel="noopener noreferrer"
											className="group flex items-center justify-center w-8 h-8 rounded-lg bg-white/40 dark:bg-slate-800/40 backdrop-blur-sm border border-white/30 dark:border-slate-700/30 text-slate-600 hover:text-black dark:text-slate-400 dark:hover:text-white hover:bg-white/60 dark:hover:bg-slate-800/60 hover:border-slate-300/50 dark:hover:border-slate-600/50 transition-all duration-200 shadow-sm hover:shadow-md"
											title="X (Twitter)"
											aria-label="X (Twitter)"
										>
											<SiX className="w-4 h-4" />
										</a>
									)}
									{/* Instagram Link */}
									{publication.links.instagram && (
										<a
											href={publication.links.instagram}
											target="_blank"
											rel="noopener noreferrer"
											className="group flex items-center justify-center w-8 h-8 rounded-lg bg-white/40 dark:bg-slate-800/40 backdrop-blur-sm border border-white/30 dark:border-slate-700/30 text-slate-600 hover:text-pink-500 dark:text-slate-400 dark:hover:text-pink-400 hover:bg-white/60 dark:hover:bg-slate-800/60 hover:border-pink-300/50 dark:hover:border-pink-500/50 transition-all duration-200 shadow-sm hover:shadow-md"
											title="Instagram"
											aria-label="Instagram"
										>
											<FaInstagram className="w-4 h-4" />
										</a>
									)}
									{/* GitHub Link */}
									{publication.links.github && (
										<a
											href={publication.links.github}
											target="_blank"
											rel="noopener noreferrer"
											className="group flex items-center justify-center w-8 h-8 rounded-lg bg-white/40 dark:bg-slate-800/40 backdrop-blur-sm border border-white/30 dark:border-slate-700/30 text-slate-600 hover:text-slate-900 dark:text-slate-400 dark:hover:text-white hover:bg-white/60 dark:hover:bg-slate-800/60 hover:border-slate-300/50 dark:hover:border-slate-600/50 transition-all duration-200 shadow-sm hover:shadow-md"
											title="GitHub"
											aria-label="GitHub"
										>
											<FaGithub className="w-4 h-4" />
										</a>
									)}
									{/* LinkedIn Link */}
									{publication.links.linkedin && (
										<a
											href={publication.links.linkedin}
											target="_blank"
											rel="noopener noreferrer"
											className="group flex items-center justify-center w-8 h-8 rounded-lg bg-white/40 dark:bg-slate-800/40 backdrop-blur-sm border border-white/30 dark:border-slate-700/30 text-slate-600 hover:text-blue-600 dark:text-slate-400 dark:hover:text-blue-400 hover:bg-white/60 dark:hover:bg-slate-800/60 hover:border-blue-300/50 dark:hover:border-blue-500/50 transition-all duration-200 shadow-sm hover:shadow-md"
											title="LinkedIn"
											aria-label="LinkedIn"
										>
											<FaLinkedin className="w-4 h-4" />
										</a>
									)}
									{/* Website Link */}
									{publication.links.website && (
										<a
											href={publication.links.website}
											target="_blank"
											rel="noopener noreferrer"
											className="group flex items-center justify-center w-8 h-8 rounded-lg bg-white/40 dark:bg-slate-800/40 backdrop-blur-sm border border-white/30 dark:border-slate-700/30 text-slate-600 hover:text-blue-500 dark:text-slate-400 dark:hover:text-blue-400 hover:bg-white/60 dark:hover:bg-slate-800/60 hover:border-blue-300/50 dark:hover:border-blue-500/50 transition-all duration-200 shadow-sm hover:shadow-md"
											title="Website"
											aria-label="Website"
										>
											<FaGlobe className="w-4 h-4" />
										</a>
									)}
									{/* Hashnode Link */}
									{publication.links.hashnode && (
										<a
											href={publication.links.hashnode}
											target="_blank"
											rel="noopener noreferrer"
											className="group flex items-center justify-center w-8 h-8 rounded-lg bg-white/40 dark:bg-slate-800/40 backdrop-blur-sm border border-white/30 dark:border-slate-700/30 text-slate-600 hover:text-blue-600 dark:text-slate-400 dark:hover:text-blue-400 hover:bg-white/60 dark:hover:bg-slate-800/60 hover:border-blue-300/50 dark:hover:border-blue-500/50 transition-all duration-200 shadow-sm hover:shadow-md"
											title="Hashnode"
											aria-label="Hashnode"
										>
											<SiHashnode className="w-4 h-4" />
										</a>
									)}
								</div>
							</div>
						)}
					</div>

					{/* Posts list */}
					{posts.length > 0 && <MinimalPosts context="home" posts={posts} />}
					{!loadedMore && pageInfo.hasNextPage && pageInfo.endCursor && (
						<button 
							onClick={loadMore}
							className="w-full sm:w-auto px-6 py-3 rounded-xl bg-blue-500/80 dark:bg-blue-600/80 backdrop-blur-md text-white hover:bg-blue-600/90 dark:hover:bg-blue-500/90 border border-blue-400/30 dark:border-blue-500/30 transition-all duration-200 text-sm sm:text-base font-medium shadow-glass-light dark:shadow-glass-dark hover:shadow-glass-hover"
						>
							Load more
						</button>
					)}
					{loadedMore && pageInfo.hasNextPage && pageInfo.endCursor && (
						<Waypoint onEnter={loadMore} bottomOffset={'10%'} />
					)}
					<Footer />
				</Container>
			</Layout>
		</AppProvider>
	);
}

export const getStaticProps: GetStaticProps<Props> = async () => {
	const data = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
		GQL_ENDPOINT,
		PostsByPublicationDocument,
		{
			first: 20,
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const publication = data.publication;
	if (!publication) {
		return {
			notFound: true,
		};
	}
	const initialPosts = (publication.posts.edges ?? []).map((edge) => edge.node);

	return {
		props: {
			publication,
			initialPosts,
			initialPageInfo: publication.posts.pageInfo,
		},
		revalidate: 1,
	};
};
