import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import { Waypoint } from 'react-waypoint';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { MinimalPosts } from '../components/minimal-posts';
import { PersonalHeader } from '../components/personal-theme-header';
import {
	FaGithub,
	FaLinkedin,
	FaInstagram,
	FaRss,
	FaGlobe,
} from 'react-icons/fa';
import {
	SiHashnode,
	SiX,
} from 'react-icons/si';
import {
	MorePostsByPublicationDocument,
	MorePostsByPublicationQuery,
	MorePostsByPublicationQueryVariables,
	PageInfoFragment,
	PostFragment,
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
	PublicationFragment,
} from '../generated/graphql';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;

type Props = {
	publication: PublicationFragment;
	initialPosts: PostFragment[];
	initialPageInfo: PageInfoFragment;
};

export default function Index({ publication, initialPosts, initialPageInfo }: Props) {
	const [posts, setPosts] = useState<PostFragment[]>(initialPosts);
	const [pageInfo, setPageInfo] = useState<Props['initialPageInfo']>(initialPageInfo);
	const [isLoading, setIsLoading] = useState(false);

	const loadMore = async () => {
		if (isLoading || !pageInfo.hasNextPage || !pageInfo.endCursor) {
			return;
		}

		setIsLoading(true);
		try {
			const data = await request<MorePostsByPublicationQuery, MorePostsByPublicationQueryVariables>(
				GQL_ENDPOINT,
				MorePostsByPublicationDocument,
				{
					first: 8,
					host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
					after: pageInfo.endCursor,
				},
			);
			if (data.publication) {
				const newPosts = data.publication.posts.edges.map((edge) => edge.node);
				setPosts([...posts, ...newPosts]);
				setPageInfo(data.publication.posts.pageInfo);
			}
		} catch (error) {
			console.error('Error loading more posts:', error);
		} finally {
			setIsLoading(false);
		}
	};
	return (
		<AppProvider publication={publication}>
			<Layout>
				<Head>
					<title>{publication.title}</title>
					<meta
						name="description"
						content={
							publication.descriptionSEO || publication.title || `${publication.author.name}'s Blog`
						}
					/>
					<meta property="twitter:card" content="summary_large_image" />
					<meta property="twitter:title" content={publication.displayTitle || publication.title || 'Hashnode Blog Starter Kit'} />
					<meta property="twitter:description" content={publication.descriptionSEO || publication.title || `${publication.author.name}'s Blog`} />
					<meta
						property="og:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<meta
						property="twitter:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{
							__html: JSON.stringify(addPublicationJsonLd(publication)),
						}}
					/>
				</Head>
				<Container className="mx-auto flex max-w-7xl flex-col items-stretch gap-6 sm:gap-8 md:gap-10 py-6 sm:py-8 md:py-10 min-h-full">
					<PersonalHeader />

					{/* About this publication */}
					<div className="rounded-2xl bg-white dark:bg-[#121212]">
						<div className="flex flex-col sm:flex-row gap-4 sm:gap-6 p-4 sm:p-6">
							{/* Left: Large Avatar */}
							{publication.author?.profilePicture && (
								<div className="flex-shrink-0">
									<Image
										src={publication.author.profilePicture}
										alt={publication.author.name}
										className="h-32 w-32 sm:h-48 sm:w-48 rounded-full"
										width={192}
										height={192}
									/>
								</div>
							)}

							{/* Right: Stacked Information Blocks */}
							<div className="flex-1 space-y-4">
								{/* Top Block: Author Info */}
								{publication.author && (
									<div className="space-y-2 rounded-lg border border-slate-200 dark:border-neutral-800 p-4">
										<div className="space-y-1">
											<p className="text-lg sm:text-xl font-bold text-slate-900 dark:text-[hsla(0,0%,100%,.87)]">
												{publication.author.name}
											</p>
											{publication.author.tagline && (
												<p className="text-sm text-slate-600 dark:text-[hsla(0,0%,100%,.6)]">
													{publication.author.tagline}
												</p>
											)}
										</div>
										{publication.author.bio?.html && (
											<div
												className="prose prose-xs sm:prose-sm prose-slate dark:prose-invert max-w-none"
												dangerouslySetInnerHTML={{ __html: publication.author.bio.html }}
											/>
										)}
									</div>
								)}

								{/* Middle Block: About Publication */}
								{(publication.about?.html || publication.descriptionSEO) && (
									<div className="space-y-2 rounded-lg border border-slate-200 dark:border-neutral-800 p-4">
										<h2 className="text-base sm:text-lg font-bold text-slate-900 dark:text-[hsla(0,0%,100%,.87)]">
											About this publication
										</h2>
										{publication.about?.html ? (
											<div
												className="prose prose-xs sm:prose-sm prose-slate dark:prose-invert max-w-none"
												dangerouslySetInnerHTML={{ __html: publication.about.html }}
											/>
										) : (
											<p className="text-sm text-slate-600 dark:text-[hsla(0,0%,100%,.6)]">
												{publication.descriptionSEO || `Welcome to ${publication.title}'s blog.`}
											</p>
										)}
									</div>
								)}

							</div>
						</div>

						{/* Bottom Block: Social Links - Full Width */}
						{publication.links && (
							<div className="space-y-2 rounded-lg border border-slate-200 dark:border-neutral-800 p-4 mt-4 mx-4 sm:mx-6">
								<h3 className="text-base sm:text-lg font-bold text-slate-900 dark:text-[hsla(0,0%,100%,.87)] mb-3">
									Socials
								</h3>
								<div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
									{/* RSS Link */}
									<a
										href="/rss.xml"
										target="_blank"
										rel="noopener noreferrer"
										className="group flex items-center gap-2 px-3 py-2 rounded-lg bg-white dark:bg-[#121212] border border-slate-200 dark:border-neutral-800 text-slate-700 dark:text-[hsla(0,0%,100%,.6)] hover:border-slate-300 dark:hover:border-neutral-700 transition-all duration-200"
										title="RSS Feed"
										aria-label="RSS Feed"
									>
										<FaRss className="w-4 h-4" />
										<span className="text-sm font-medium">RSS</span>
									</a>
									{/* Twitter/X Link */}
									{publication.links.twitter && (
										<a
											href={publication.links.twitter}
											target="_blank"
											rel="noopener noreferrer"
											className="group flex items-center gap-2 px-3 py-2 rounded-lg bg-white dark:bg-[#121212] border border-slate-200 dark:border-neutral-800 text-slate-700 dark:text-[hsla(0,0%,100%,.6)] hover:border-slate-300 dark:hover:border-neutral-700 transition-all duration-200"
											title="X (Twitter)"
											aria-label="X (Twitter)"
										>
											<SiX className="w-4 h-4" />
											<span className="text-sm font-medium">X</span>
										</a>
									)}
									{/* Instagram Link */}
									{publication.links.instagram && (
										<a
											href={publication.links.instagram}
											target="_blank"
											rel="noopener noreferrer"
											className="group flex items-center gap-2 px-3 py-2 rounded-lg bg-white dark:bg-[#121212] border border-slate-200 dark:border-neutral-800 text-slate-700 dark:text-[hsla(0,0%,100%,.6)] hover:border-slate-300 dark:hover:border-neutral-700 transition-all duration-200"
											title="Instagram"
											aria-label="Instagram"
										>
											<FaInstagram className="w-4 h-4" />
											<span className="text-sm font-medium">Instagram</span>
										</a>
									)}
									{/* GitHub Link */}
									{publication.links.github && (
										<a
											href={publication.links.github}
											target="_blank"
											rel="noopener noreferrer"
											className="group flex items-center gap-2 px-3 py-2 rounded-lg bg-white dark:bg-[#121212] border border-slate-200 dark:border-neutral-800 text-slate-700 dark:text-[hsla(0,0%,100%,.6)] hover:border-slate-300 dark:hover:border-neutral-700 transition-all duration-200"
											title="GitHub"
											aria-label="GitHub"
										>
											<FaGithub className="w-4 h-4" />
											<span className="text-sm font-medium">GitHub</span>
										</a>
									)}
									{/* LinkedIn Link */}
									{publication.links.linkedin && (
										<a
											href={publication.links.linkedin}
											target="_blank"
											rel="noopener noreferrer"
											className="group flex items-center gap-2 px-3 py-2 rounded-lg bg-white dark:bg-[#121212] border border-slate-200 dark:border-neutral-800 text-slate-700 dark:text-[hsla(0,0%,100%,.6)] hover:border-slate-300 dark:hover:border-neutral-700 transition-all duration-200"
											title="LinkedIn"
											aria-label="LinkedIn"
										>
											<FaLinkedin className="w-4 h-4" />
											<span className="text-sm font-medium">LinkedIn</span>
										</a>
									)}
									{/* Website Link */}
									{publication.links.website && (
										<a
											href={publication.links.website}
											target="_blank"
											rel="noopener noreferrer"
											className="group flex items-center gap-2 px-3 py-2 rounded-lg bg-white dark:bg-[#121212] border border-slate-200 dark:border-neutral-800 text-slate-700 dark:text-[hsla(0,0%,100%,.6)] hover:border-slate-300 dark:hover:border-neutral-700 transition-all duration-200"
											title="Website"
											aria-label="Website"
										>
											<FaGlobe className="w-4 h-4" />
											<span className="text-sm font-medium">Website</span>
										</a>
									)}
									{/* Hashnode Link */}
									{publication.links.hashnode && (
										<a
											href={publication.links.hashnode}
											target="_blank"
											rel="noopener noreferrer"
											className="group flex items-center gap-2 px-3 py-2 rounded-lg bg-white dark:bg-[#121212] border border-slate-200 dark:border-neutral-800 text-slate-700 dark:text-[hsla(0,0%,100%,.6)] hover:border-slate-300 dark:hover:border-neutral-700 transition-all duration-200"
											title="Hashnode"
											aria-label="Hashnode"
										>
											<SiHashnode className="w-4 h-4" />
											<span className="text-sm font-medium">Hashnode</span>
										</a>
									)}
								</div>
							</div>
						)}
					</div>

					{/* Posts list */}
					{posts.length > 0 && <MinimalPosts context="home" posts={posts} />}

					{pageInfo.hasNextPage && pageInfo.endCursor && (
						<div className="flex justify-center py-8">
							<Waypoint onEnter={loadMore} bottomOffset={'20%'} />
							{isLoading && (
								<div className="flex items-center gap-2 text-slate-500 dark:text-slate-400">
									<div className="w-5 h-5 border-2 border-blue-500 border-t-transparent rounded-full animate-spin"></div>
									<span className="text-sm font-medium">Loading more posts...</span>
								</div>
							)}
						</div>
					)}
					<Footer />
				</Container>
			</Layout>
		</AppProvider>
	);
}

export const getStaticProps: GetStaticProps<Props> = async () => {
	try {
		const data = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
			GQL_ENDPOINT,
			PostsByPublicationDocument,
			{
				first: 8,
				host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
			},
		);

		const publication = data.publication;
		if (!publication) {
			return {
				notFound: true,
			};
		}
		const initialPosts = (publication.posts.edges ?? []).map((edge) => edge.node);

		return {
			props: {
				publication,
				initialPosts,
				initialPageInfo: publication.posts.pageInfo,
			},
			revalidate: 1,
		};
	} catch (error) {
		console.error('Error fetching data in index getStaticProps:', error);
		return {
			notFound: true,
			revalidate: 1,
		};
	}
};
